apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        imagePullPolicy: Always
        image: obsidiandynamics/kafdrop:3.23.0
        ports:
        - containerPort: 9000
          name: http
        env:
        - name : KAFKA_BROKERCONNECT
          value: 'b-2.XXXX.XXXXXX.c3.kafka.ap-northeast-1.amazonaws.com:9092,b-1.XXXX.XXXXXX.c3.kafka.ap-northeast-1.amazonaws.com:9092'
        - name : JVM_OPTS
          value: '-Xms32M -Xmx64M'
        - name : SERVER_SERVLET_CONTEXTPATH
          value: '/'
      restartPolicy: Always
